/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Homless_Models (https://sketchfab.com/hl_models)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/our-moon-0daa5bd2ddd14f4bbb8f0d2d5c2df6e1
Title: Our Moon
*/
/* eslint-disable react/no-unknown-property */
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
	const { nodes, materials } = useGLTF('/moon/scene.gltf');
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
						<mesh
							geometry={nodes.lroc_color_poles_16k_lroc_color_poles_16k_0.geometry}
							material={materials.lroc_color_poles_16k}
						/>
						<mesh
							geometry={nodes.lroc_color_poles_16k_lroc_color_poles_16k_0_1.geometry}
							material={materials.lroc_color_poles_16k}
						/>
						<mesh
							geometry={nodes.lroc_color_poles_16k_lroc_color_poles_16k_0_2.geometry}
							material={materials.lroc_color_poles_16k}
						/>
						<mesh
							geometry={nodes.lroc_color_poles_16k_lroc_color_poles_16k_0_3.geometry}
							material={materials.lroc_color_poles_16k}
						/>
						<mesh
							geometry={nodes.lroc_color_poles_16k_lroc_color_poles_16k_0_4.geometry}
							material={materials.lroc_color_poles_16k}
						/>
						<mesh
							geometry={nodes.lroc_color_poles_16k_lroc_color_poles_16k_0_5.geometry}
							material={materials.lroc_color_poles_16k}
						/>
						<mesh
							geometry={nodes.lroc_color_poles_16k_lroc_color_poles_16k_0_6.geometry}
							material={materials.lroc_color_poles_16k}
						/>
						<mesh
							geometry={nodes.lroc_color_poles_16k_lroc_color_poles_16k_0_7.geometry}
							material={materials.lroc_color_poles_16k}
						/>
						<mesh
							geometry={nodes.lroc_color_poles_16k_lroc_color_poles_16k_0_8.geometry}
							material={materials.lroc_color_poles_16k}
						/>
						<mesh
							geometry={nodes.lroc_color_poles_16k_lroc_color_poles_16k_0_9.geometry}
							material={materials.lroc_color_poles_16k}
						/>
						<mesh
							geometry={nodes.lroc_color_poles_16k_lroc_color_poles_16k_0_10.geometry}
							material={materials.lroc_color_poles_16k}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/moon/scene.gltf');
